# ---------------------------------------------------------------------------------------------------------------------
# Generates all derived project metadata from metadata.json.
#
# Generic Steam Workshop metadata (README.md and workshop/workshop.txt) is generated by steam-workshop-devops.
# Scrap Mechanic's source/description.json is generated locally because it is game-specific metadata.
# ---------------------------------------------------------------------------------------------------------------------

$ErrorActionPreference = "Stop"

$Root = Split-Path $PSScriptRoot -Parent
$DevOpsRepository = "https://github.com/community-owned-workshop/steam-workshop-devops.git"

# Use the feature branch while testing. Change this to v1 (or the released version)
# once the generic metadata generator has been released.
$DevOpsVersion = "feature/scrap-mechanic"

$TemporaryDirectory = Join-Path `
    ([System.IO.Path]::GetTempPath()) `
    ("cow-steam-workshop-devops-" + [guid]::NewGuid())

$PreviousRollForward = $env:DOTNET_ROLL_FORWARD
$LocationPushed = $false

try {
    $env:DOTNET_ROLL_FORWARD = "Major"

    # Download exactly the DevOps version used to generate the repository metadata.
    git -c advice.detachedHead=false clone `
        --quiet `
        --depth 1 `
        --branch $DevOpsVersion `
        $DevOpsRepository `
        $TemporaryDirectory

    if ($LASTEXITCODE -ne 0) {
        throw "Could not download steam-workshop-devops@$DevOpsVersion."
    }

    Push-Location $Root
    $LocationPushed = $true

    # Generate the generic repository and Steam Workshop metadata first.
    & "$TemporaryDirectory/metadata/generate-metadata.ps1"

    if ($LASTEXITCODE -ne 0) {
        throw "Metadata generation failed."
    }

    # Scrap Mechanic also expects description.json in the mod root. Keep the stable
    # localId in metadata.json; generating a new UUID on every run would make the
    # same repository appear as a different local mod to Scrap Mechanic.
    $Metadata = Get-Content (Join-Path $Root "metadata.json") -Raw | ConvertFrom-Json

    if (-not $Metadata.scrapMechanic.localId) {
        throw "metadata.json is missing scrapMechanic.localId."
    }

    if (-not $Metadata.workshop.id) {
        throw "metadata.json is missing workshop.id."
    }

    $ScrapMechanicVersion = 0
    if (-not [int]::TryParse(([string]$Metadata.version).Split('.')[0], [ref]$ScrapMechanicVersion)) {
        throw "metadata.json version '$($Metadata.version)' has no numeric major version for Scrap Mechanic description.json."
    }

    # Mirror the structure written by Scrap Mechanic's Mod Tool. fileId is numeric,
    # while localId remains the stable UUID assigned to this mod.
    $Description = [ordered]@{
        allow_add_mods = [bool]$Metadata.scrapMechanic.allowAddMods
        custom_icons   = [bool]$Metadata.scrapMechanic.customIcons
        description    = if ($Metadata.scrapMechanic.description) { [string]$Metadata.scrapMechanic.description } else { [string]$Metadata.summary }
        fileId         = [long]$Metadata.workshop.id
        localId        = [string]$Metadata.scrapMechanic.localId
        name           = [string]$Metadata.name
        type           = if ($Metadata.scrapMechanic.type) { [string]$Metadata.scrapMechanic.type } else { "Blocks and Parts" }
        version        = $ScrapMechanicVersion
    }

    $DescriptionPath = Join-Path $Root "source/description.json"
    $DescriptionJson = $Description | ConvertTo-Json -Depth 10
    [System.IO.File]::WriteAllText($DescriptionPath, $DescriptionJson + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))

    Write-Host "Generated source/description.json"
}
finally {
    if ($LocationPushed) {
        Pop-Location
    }

    if ($null -eq $PreviousRollForward) {
        Remove-Item Env:DOTNET_ROLL_FORWARD -ErrorAction SilentlyContinue
    }
    else {
        $env:DOTNET_ROLL_FORWARD = $PreviousRollForward
    }

    Remove-Item $TemporaryDirectory -Recurse -Force -ErrorAction SilentlyContinue
}
